name: Deploy App to EC2 (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

     - name: Deploy Application to EC2
  run: |
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
      echo "Connected to EC2"

      cd /home/ubuntu/app
      sudo rm -rf *
      sudo git clone https://github.com/${{ github.repository }} .

      echo "Building Docker..."
      sudo docker build -t webapp .

      echo "Restarting container..."
      sudo docker stop webapp || true
      sudo docker rm webapp || true
      sudo docker run -d -p 80:80 --name webapp webapp
    EOF

