name: Deploy App to EC2 (Docker CI/CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ubuntu@13.201.222.164 << 'EOF'
            echo "Connected successfully to EC2"

            mkdir -p /home/ubuntu/app
            cd /home/ubuntu/app

            sudo rm -rf /home/ubuntu/app/*
            sudo git clone https://github.com/${{ github.repository }} /home/ubuntu/app

            sudo docker build -t webapp .

            sudo docker stop webapp || true
            sudo docker rm webapp || true

            sudo docker run -d -p 80:80 --name webapp webapp

            echo "Deployment completed successfully!"
          EOF
